// 한밤의 전쟁 (The War Within) 기준 생존기 기본값
// WCL은 영어로 스킬명을 반환하므로 영어 이름 사용
// 유저가 설정창에서 직접 수정 가능합니다

export const DEFAULT_DEFENSIVE_SETTINGS: Record<string, string[]> = {
  "전사-보호":        ["Shield Wall", "Last Stand", "Rallying Cry"],
  "전사-분노":        ["Die by the Sword", "Ignore Pain"],
  "전사-무기":        ["Die by the Sword", "Rallying Cry"],
  "성기사-신성":      ["Divine Shield", "Blessing of Protection"],
  "성기사-보호":      ["Ardent Defender", "Guardian of Ancient Kings", "Divine Shield"],
  "성기사-응징":      ["Divine Shield", "Blessing of Protection"],
  "사냥꾼-야수":      ["Aspect of the Turtle"],
  "사냥꾼-사격":      ["Aspect of the Turtle"],
  "사냥꾼-생존":      ["Aspect of the Turtle"],
  "도적-암살":        ["Evasion", "Crimson Vial", "Cloak of Shadows"],
  "도적-무법":        ["Evasion", "Crimson Vial", "Cloak of Shadows"],
  "도적-잠행":        ["Evasion", "Crimson Vial", "Cloak of Shadows"],
  "사제-수양":        ["Power Word: Barrier", "Desperate Prayer"],
  "사제-신성":        ["Desperate Prayer"],
  "사제-암흑":        ["Dispersion"],
  "죽음의 기사-혈기":  ["Vampiric Blood", "Icebound Fortitude"],
  "죽음의 기사-냉기":  ["Icebound Fortitude"],
  "죽음의 기사-부정":  ["Icebound Fortitude"],
  "주술사-정기":      ["Astral Shift"],
  "주술사-향상":      ["Astral Shift"],
  "주술사-복원":      ["Astral Shift"],
  "마법사-냉기":      ["Ice Barrier", "Ice Block"],
  "마법사-화염":      ["Blazing Barrier"],
  "마법사-신비":      ["Prismatic Barrier"],
  "흑마법사-고통":    ["Unending Resolve", "Dark Pact"],
  "흑마법사-악마":    ["Unending Resolve"],
  "흑마법사-파괴":    ["Unending Resolve"],
  "수도사-풍운":      ["Diffuse Magic", "Dampen Harm"],
  "수도사-양조":      ["Fortifying Brew"],
  "수도사-신비":      ["Life Cocoon"],
  "드루이드-조화":    ["Barkskin"],
  "드루이드-야성":    ["Survival Instincts", "Barkskin"],
  "드루이드-수호":    ["Survival Instincts", "Barkskin"],
  "드루이드-회복":    ["Barkskin"],
  "악마사냥꾼-악마 사냥": ["Blur", "Netherwalk"],
  "악마사냥꾼-복수":  ["Metamorphosis", "Fiery Brand"],
  "기원사-황폐":      ["Obsidian Scales"],
  "기원사-보존":      ["Obsidian Scales", "Rewind"],
  "기원사-증강":      ["Obsidian Scales"],
};

// 블러드러스트 계열 스킬 이름 (영어)
export const BLOODLUST_ABILITY_NAMES = new Set([
  "bloodlust",
  "heroism",
  "time warp",
  "primal rage",
  "fury of the aspects",
  "ancient hysteria",
  "drums of fury",
  "drums of the forgotten kings",
  // 한국어 클라이언트 대비 (혹시 몰라)
  "피의욕망",
  "영웅심",
  "시간 왜곡",
  "원초적 분노",
  "위상의 격노",
  "고대의 광기",
  "굉음의 북",
]);
