import type { DefensiveEntry } from '@/app/types/raidAnalysis';

// 한밤의 전쟁 (The War Within) 기준 생존기 기본값
// WCL은 영어로 스킬명을 반환하므로 영어 이름 사용
export const DEFAULT_DEFENSIVE_SETTINGS: Record<string, DefensiveEntry[]> = {
  "전사-보호":        [{ name: "Shield Wall" }, { name: "Last Stand" }, { name: "Rallying Cry" }],
  "전사-분노":        [{ name: "Die by the Sword" }, { name: "Ignore Pain" }],
  "전사-무기":        [{ name: "Die by the Sword" }, { name: "Rallying Cry" }],
  "성기사-신성":      [{ name: "Divine Shield" }, { name: "Blessing of Protection" }],
  "성기사-보호":      [{ name: "Ardent Defender" }, { name: "Guardian of Ancient Kings" }, { name: "Divine Shield" }],
  "성기사-응징":      [{ name: "Divine Shield" }, { name: "Blessing of Protection" }],
  "사냥꾼-야수":      [{ name: "Aspect of the Turtle" }],
  "사냥꾼-사격":      [{ name: "Aspect of the Turtle" }],
  "사냥꾼-생존":      [{ name: "Aspect of the Turtle" }],
  "도적-암살":        [{ name: "Evasion" }, { name: "Crimson Vial" }, { name: "Cloak of Shadows" }],
  "도적-무법":        [{ name: "Evasion" }, { name: "Crimson Vial" }, { name: "Cloak of Shadows" }],
  "도적-잠행":        [{ name: "Evasion" }, { name: "Crimson Vial" }, { name: "Cloak of Shadows" }],
  "사제-수양":        [{ name: "Power Word: Barrier" }, { name: "Desperate Prayer" }],
  "사제-신성":        [{ name: "Desperate Prayer" }],
  "사제-암흑":        [{ name: "Dispersion" }],
  "죽음의 기사-혈기":  [{ name: "Vampiric Blood" }, { name: "Icebound Fortitude" }],
  "죽음의 기사-냉기":  [{ name: "Icebound Fortitude" }],
  "죽음의 기사-부정":  [{ name: "Icebound Fortitude" }],
  "주술사-정기":      [{ name: "Astral Shift" }],
  "주술사-향상":      [{ name: "Astral Shift" }],
  "주술사-복원":      [{ name: "Astral Shift" }],
  "마법사-냉기":      [{ name: "Ice Barrier" }, { name: "Ice Block" }],
  "마법사-화염":      [{ name: "Blazing Barrier" }],
  "마법사-신비":      [{ name: "Prismatic Barrier" }],
  "흑마법사-고통":    [{ name: "Unending Resolve" }, { name: "Dark Pact" }],
  "흑마법사-악마":    [{ name: "Unending Resolve" }],
  "흑마법사-파괴":    [{ name: "Unending Resolve" }],
  "수도사-풍운":      [{ name: "Diffuse Magic" }, { name: "Dampen Harm" }],
  "수도사-양조":      [{ name: "Fortifying Brew" }],
  "수도사-신비":      [{ name: "Life Cocoon" }],
  "드루이드-조화":    [{ name: "Barkskin" }],
  "드루이드-야성":    [{ name: "Survival Instincts" }, { name: "Barkskin" }],
  "드루이드-수호":    [{ name: "Survival Instincts" }, { name: "Barkskin" }],
  "드루이드-회복":    [{ name: "Barkskin" }],
  "악마사냥꾼-악마 사냥": [{ name: "Blur" }, { name: "Netherwalk" }],
  "악마사냥꾼-복수":  [{ name: "Metamorphosis" }, { name: "Fiery Brand" }],
  "기원사-황폐":      [{ name: "Obsidian Scales" }],
  "기원사-보존":      [{ name: "Obsidian Scales" }, { name: "Rewind" }],
  "기원사-증강":      [{ name: "Obsidian Scales" }],
};

export const BLOODLUST_ABILITY_NAMES = new Set([
  "bloodlust", "heroism", "time warp", "primal rage",
  "fury of the aspects", "ancient hysteria",
  "drums of fury", "drums of the forgotten kings",
  "피의욕망", "영웅심", "시간 왜곡", "원초적 분노",
  "위상의 격노", "고대의 광기", "굉음의 북",
]);
